# Generated by Django 6.0.3 on 2026-03-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_profile_last_seen_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='typing_in',
            field=models.IntegerField(default=0),
        ),
    ]
