# Generated by Django 6.0.3 on 2026-03-08 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_alter_chat_id_alter_folder_id_alter_message_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='color',
            field=models.CharField(default='#3b82f6', max_length=20),
        ),
        migrations.AlterField(
            model_name='folder',
            name='chats',
            field=models.ManyToManyField(blank=True, to='chat.chat'),
        ),
    ]
